services:
  Adeelnawaz\PolrApiBundle\Service\PolrApiService:
    class: Adeelnawaz\PolrApiBundle\Service\PolrApiService
    arguments:
      - '%polr_api.api_url%'
      - '%polr_api.api_key%'
      - '%polr_api.api_quota%'